#!/usr/bin/env php
<?php

if (!defined('DS')) {
    define('DS', DIRECTORY_SEPARATOR);
}
if (!defined('ROOT')) {
    define('ROOT', realpath(__DIR__) . DS);
}
echo "=========================\n";
echo "  HexaPHP CLI \n";
echo "=========================\n";

require_once ROOT . 'core' .DS. 'autoload.php';

use HexaPHP\Core\Cmd\CreateAppCmd;
use HexaPHP\Core\Cmd\CreateLibCmd;
use HexaPHP\Core\Cmd\ServeAppCmd;

$args = array_slice($argv, 1);

if (count($args) < 2) {
    echo "Usage: run <Cmd> <name>\n";
    exit(1);
}

$Cmd = array_shift($args);
$name = array_shift($args);

switch (strtolower($Cmd)) {
    case 'install':
        exec("composer install --prefer-dist --no-cache");
        break;
    case 'create:app':
        $createCmd = new CreateAppCmd();
        $createCmd->execute([$name, ...$args]);
        break;
    case 'create:lib':
        $createCmd = new CreateLibCmd();
        $createCmd->execute([$name, ...$args]);
        break;
    case 'serve:app':
        $createCmd = new ServeAppCmd();
        $createCmd->execute([$name, ...$args]);
        break;
    case 'build:app':
        echo "Deploying {$name}...\n";
        exec("composer install --prefer-dist --no-cache");
        exec("docker build -t hexapp:latest .");
        
        if ($name != "."){
            exec("docker build -t hexapp/$name --build-arg BASE_IMAGE=hexapp:latest ./apps/$name");
        }
        break;
    case 'test:app':
        echo "Testing {$name}...\n";
        exec("composer test");
        break;
    case 'deploy:app':
        echo "Deploying {$name}...\n";
        $env = $args[2] ?? 'local';
        // exec("scp package.zip user@production:/path/to/destination");
        break;
        
    default:
        echo "Unknown Cmd: {$Cmd}\n";
        exit(1);
}
