#!/usr/bin/env php
<?php

if (!defined('DS')) {
    define('DS', DIRECTORY_SEPARATOR);
}
if (!defined('ROOT')) {
    define('ROOT', realpath(__DIR__) . DS);
}
echo "=========================\n";
echo "  HexMonoPHP CLI \n";
echo "=========================\n";

require_once ROOT . 'core' .DS. 'autoload.php';

use Core\Cmd\CreateAppCmd;
use Core\Cmd\CreateLibCmd;
use Core\Cmd\ServeAppCmd;

$args = array_slice($argv, 1);

if (count($args) < 2) {
    echo "Usage: run <Cmd> <name>\n";
    exit(1);
}

$Cmd = strtolower($args[0]);
$name = $args[1];

switch ($Cmd) {
    case 'create:app':
        $createCmd = new CreateAppCmd();
        $createCmd->execute([$name]);
        break;
    case 'create:lib':
        $createCmd = new CreateLibCmd();
        $createCmd->execute([$name]);
        break;
    case 'serve:app':
        $createCmd = new ServeAppCmd();
        $createCmd->execute([$name]);
        break;
    case 'build':
        echo "Deploying {$name}...\n";
        exec("composer install --no-dev --optimize-autoloader");
        exec("composer package");
        break;
    case 'test:app':
        echo "Testing {$name}...\n";
        exec("composer test");
        break;
    case 'deploy':
        echo "Deploying {$name}...\n";
        exec("scp package.zip user@production:/path/to/destination");
        break;
        
    default:
        echo "Unknown Cmd: {$Cmd}\n";
        exit(1);
}
